# Generated by Django 4.2.6 on 2023-10-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=500)),
                ('new_date', models.DateField()),
                ('news_description', models.TextField()),
                ('news_image', models.ImageField(upload_to='static/media/')),
            ],
        ),
    ]
